module.exports = {
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  DB_UNKNOWN_ERROR: 'DB_UNKNOWN_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  ERR_PARAMS_PRE: 'ERR_PARAMS_PRE',
  ILLEGAL_OPERATION: 'ILLEGAL_OPERATION',
  CANDIDATE_IN_THEME: 'CANDIDATE_IN_THEME',
  SEND_MQ_ERROR: 'SEND_MQ_ERROR',
  MULTIPLE_VOTING: 'MULTIPLE_VOTING',
  VERIFICATION_EXPIRED: 'VERIFICATION_EXPIRED',
};
